### ISSUE TITLE
restart camera

### ISSUE THREAD

**Issue by AmitNehra1** [MR-MaoJiu/beauty_cam#1]
when i start app then the camera works properly but once i changed the screen and then came to camerascreen then the camera not works it black screen no capture videos.

**Comment by MR-MaoJiu** [comment]
OK, I will fix it as soon as possible! You can pay attention to this project.

**Comment by MR-MaoJiu** [comment]
Already fixed, please use `beauty_cam: ^1.0.4`[https://pub.dev/packages/beauty_cam](https://pub.dev/packages/beauty_cam)
