### ISSUE TITLE
example 运行不起来3.22.2

### ISSUE THREAD

**Issue by sunjiaming** [MR-MaoJiu/beauty_cam#15]
![image](https://github.com/user-attachments/assets/8a3c238d-f769-467b-b3a6-81ead658bce2)

@MR-MaoJiu

**Comment by MR-MaoJiu** [comment]
这边应该是你环境的问题错误已经提示出来了你flutter缺少文件

**Comment by MR-MaoJiu** [comment]
目前看来是你环境的问题你可以调整一下你的环境

**Comment by sunjiaming** [comment]
OK，谢谢

**Comment by sunjiaming** [comment]
flutter precache  fvm管理的版本确实缺少这个文件，使用这个命令已解决。

**Comment by sunjiaming** [comment]
![image](https://github.com/user-attachments/assets/90280d0f-f84a-4e64-a6d9-20d60a31d4c6)


@MR-MaoJiu  问题又来了，幸苦再看看

**Comment by MR-MaoJiu** [comment]
排查一下权限有没有给
