### ISSUE TITLE
Full screen video recording

### ISSUE THREAD

**Issue by zamargab** [MR-MaoJiu/beauty_cam#5]
Thanks for this awesome package. I want the recording screen to take the entire screen height and screen width, is this possible at the moment?

Eagerly awaiting your response.

**Comment by MR-MaoJiu** [comment]
Hello, I’m not quite clear about what you mean. If you’re referring to filling the screen with the camera image, it is currently displayed in fullscreen. However, if you want to customize it, there is currently no exposed interface to achieve that. If you need it, you can fork a copy of the code and implement it yourself. You just need to expose the width and height of Android and iOS separately!

**Comment by zamargab** [comment]
Let me provide more explanation, [This is what i want to achieve](https://firebasestorage.googleapis.com/v0/b/ogapick-88491.appspot.com/o/Screenshot%202023-10-04%20at%201.40.28%20PM.png?alt=media&token=9afbe125-85b6-4d61-a191-8b3d7630d926&_gl=1*bw7kov*_ga*MzE1NDI4ODkwLjE2NzA2NTg1NTg.*_ga_CW55HF8NVT*MTY5NjQyMzE0NC4xNTQuMS4xNjk2NDIzMzI1LjI0LjAuMA..)

[This is what the package produces](https://firebasestorage.googleapis.com/v0/b/ogapick-88491.appspot.com/o/Screenshot_1696423052.png?alt=media&token=06dcdc80-2955-4405-8fb9-1f4a31923dd6&_gl=1*19k1tdd*_ga*MzE1NDI4ODkwLjE2NzA2NTg1NTg.*_ga_CW55HF8NVT*MTY5NjQyMzE0NC4xNTQuMS4xNjk2NDIzNDUwLjIyLjAuMA..)

**Comment by zamargab** [comment]
[This is a more detailed view of what the package produces](https://firebasestorage.googleapis.com/v0/b/ogapick-88491.appspot.com/o/Screenshot%202023-10-04%20at%201.46.07%20PM.png?alt=media&token=f91790d3-bb0b-4a5f-a351-8c4a7056962b&_gl=1*e39b5z*_ga*MzE1NDI4ODkwLjE2NzA2NTg1NTg.*_ga_CW55HF8NVT*MTY5NjQyMzE0NC4xNTQuMS4xNjk2NDIzNjI4LjIyLjAuMA..)

**Comment by MR-MaoJiu** [comment]
![93f721cae4ef2d34003dfda012e4e0e](https://github.com/MR-MaoJiu/beauty_cam/assets/52182801/21d3f9cd-224a-4d0d-967e-bda3b00c8f6e)
This is an example of our project. You can try to run the plug-in example. I’m not sure if it’s a problem with your use. If it doesn’t work, you can choose to clone a copy of the code locally and then modify the corresponding code. I will tell you later. Or you can wait until I have time to upgrade the version.

**Comment by MR-MaoJiu** [comment]
Okay, I see what you mean, if you give me a star now I think I will fix this problem tonight😂

**Comment by MR-MaoJiu** [comment]
Sorry, I forgot my MacBook. I'll probably have to wait until after my vacation the day after tomorrow to fix this problem
/(ㄒoㄒ)/~~

**Comment by zamargab** [comment]
Ok. I will give you a star  😂, I will be expecting the update day after tomorrow. Thanks a lot. You did a great job with the package.

**Comment by MR-MaoJiu** [comment]
Thank you, I will continue to work hard, but I don’t have much time recently

**Comment by MR-MaoJiu** [comment]
I'm sorry that I can't fix this problem in the short term, because when I fixed it, I found that the resolution would be reduced. Maybe you can consider referring to the Camera plug-in to modify your code. If you have enough time, you can also clone a copy of the code. Make changes locally.

**Comment by MR-MaoJiu** [comment]
I fixed the issue and now you can use the latest version

**Comment by zamargab** [comment]
Thanks for this.
